### ISSUE TITLE
StringIndexOutOfBoundsException when creating a new PDE project

### ISSUE THREAD

**Issue by dhuebner** [eclipse-pde/eclipse.pde#724]
I'm using the following setup:

```
Eclipse DSL Tools (includes Incubating components)

Version: 2023-09 M3 (4.29.0 M3)
Build id: 20230824-1840

```

When trying to create a new Plug-in project using the "New Project..." wizard, I'm getting following error:

```
java.lang.StringIndexOutOfBoundsException: begin 0, end -1, length 24
	at java.base/java.lang.String.checkBoundsBeginEnd(String.java:4606)
	at java.base/java.lang.String.substring(String.java:2709)
	at org.eclipse.pde.internal.build.site.PDEState.lambda$7(PDEState.java:650)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.zip.ZipFile$EntrySpliterator.tryAdvance(ZipFile.java:565)
	at java.base/java.util.Spliterator.forEachRemaining(Spliterator.java:332)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at org.eclipse.pde.internal.build.site.PDEState.querySystemPackages(PDEState.java:651)
	at org.eclipse.pde.internal.build.site.PDEState.querySystemPackages(PDEState.java:515)
	at org.eclipse.pde.internal.build.site.PDEState.getSystemPackages(PDEState.java:491)
	at org.eclipse.pde.internal.core.TargetPlatformHelper.getSystemPackages(TargetPlatformHelper.java:391)
	at org.eclipse.pde.internal.core.TargetPlatformHelper.addEnvironmentProperties(TargetPlatformHelper.java:378)
	at org.eclipse.pde.internal.core.TargetPlatformHelper.getPlatformProperties(TargetPlatformHelper.java:365)
	at org.eclipse.pde.internal.core.MinimalState.initializePlatformProperties(MinimalState.java:251)
	at org.eclipse.pde.internal.core.PDEState.<init>(PDEState.java:70)
	at org.eclipse.pde.internal.core.PluginModelManager.initializeTable(PluginModelManager.java:617)
	at org.eclipse.pde.internal.core.PluginModelManager.targetReloaded(PluginModelManager.java:542)
	at org.eclipse.pde.internal.ui.wizards.plugin.NewPluginProjectWizard.lambda$0(NewPluginProjectWizard.java:129)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
```

I'm not sure if it the PDE issue, but from what I see in the stack trace it is worth to report it here.

**Comment by iloveeclipse** [comment]
This *is* a PDE issue and regression from 24e9bb548b0de8c8ea79ee70d28096e28202da31.

The code assumes all .class files should be in some directory. and does this: 
https://github.com/eclipse-pde/eclipse.pde/blob/3f5584d7ab836cd4eab0094c77fbe4ec170ef180/build/org.eclipse.pde.build/src/org/eclipse/pde/internal/build/site/PDEState.java#L660

Can you check in the IDE under installed **non modular** JRE's locations, which one could contain a jar with a class file placed directly under the jar root?

**Comment by HannesWell** [comment]
> Can you check in the IDE under installed **non modular** JRE's (anything below Java 9) locations, which one could contain a jar with a class file placed directly under the jar root?

A class in the jar root must be in the _default_ package, i.e. must not have a package declaration.
I assumed, this is not done in the JDK, but it looks like this assumption was wrong.

**Comment by dhuebner** [comment]
@iloveeclipse 
Andrey, you can download the M3 version I'm using from here:
https://download.eclipse.org/technology/epp/downloads/release/2023-09/M3/_mirrors.php

It uses the bundled vm. The default JRE is also the 17, so the same. Even thought I do have older JREs installed.

 
<img width="376" alt="Bildschirmfoto 2023-08-25 um 11 34 11" src="https://github.com/eclipse-pde/eclipse.pde/assets/454322/0aec5528-e752-4446-99d6-4475428576ce">

**Comment by iloveeclipse** [comment]
I assume that strange thing under "Internet Plug-Ins" is added automatically due https://github.com/eclipse-jdt/eclipse.jdt.debug/pull/276.

**Comment by dhuebner** [comment]
@iloveeclipse 
Now I see! You are probably looking for this WrapperGenerator guy here:
<img width="470" alt="Bildschirmfoto 2023-08-25 um 13 18 27" src="https://github.com/eclipse-pde/eclipse.pde/assets/454322/50f938d6-090c-42f1-af6d-335e74f2a2f9">

**Comment by iloveeclipse** [comment]
> You are probably looking for this WrapperGenerator guy here:

Yep. I've checked my old Java 7 install on Linux from Oracle, this seem to be something Apple specific.

I'm still curious to see what kind of JRE is inside "Library/Internet Plug-Ins/" directory...

**Comment by dhuebner** [comment]
I think it is the same as regular under 1.8.0_241 but for Java applets

<img width="472" alt="Bildschirmfoto 2023-08-25 um 13 33 23" src="https://github.com/eclipse-pde/eclipse.pde/assets/454322/b03118e9-29ad-42fe-b3a8-64b928f53e72">

**Comment by olkornii** [comment]
@iloveeclipse Maybe you know, is it the same problem and it's already fixed?

**Comment by jonahgraham** [comment]
@olkornii can you add the [RC2a](https://download.eclipse.org/eclipse/downloads/drops4/S-4.29RC2a-202309031000/) p2 update site  `https://download.eclipse.org/eclipse/updates/4.29-I-builds/I20230903-1000/` to your [available software sites](https://help.eclipse.org/latest/topic/org.eclipse.platform.doc.user/tasks/tasks-128.htm), check for updates and restart and see if you can still reproduce the problem?

**Comment by HannesWell** [comment]
> probably I have a similar problem, I'm not entirely sure, but I think it's worth mentioning here.

This does not seem to be related at all.
The only thing in common is that an `ArrayIndexOutOfBoundsException` is thrown, but the stack-tace does not mention PDE at all:
```
Problems occurred when invoking code from plug-in: "org.eclipse.core.resources".

java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at org.eclipse.jst.j2ee.internal.common.classpath.J2EEComponentClasspathUpdater$FindNodeJob.<init>(J2EEComponentClasspathUpdater.java:254)
	at org.eclipse.jst.j2ee.internal.common.classpath.J2EEComponentClasspathUpdater.createFindNodeJob(J2EEComponentClasspathUpdater.java:535)
	at org.eclipse.jst.j2ee.internal.common.classpath.J2EEComponentClasspathUpdater.resourceChanged(J2EEComponentClasspathUpdater.java:519)
	at org.eclipse.core.internal.events.NotificationManager$1.run(NotificationManager.java:321)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.NotificationManager.notify(NotificationManager.java:311)
	at org.eclipse.core.internal.events.NotificationManager.broadcastChanges(NotificationManager.java:174)
	at org.eclipse.core.internal.resources.Workspace.broadcastPostChange(Workspace.java:458)
	at org.eclipse.core.internal.resources.Workspace.endOperation(Workspace.java:1586)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2467)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2478)
	at org.eclipse.debug.core.model.Breakpoint.run(Breakpoint.java:364)
	at org.eclipse.jdt.internal.debug.core.breakpoints.JavaExceptionBreakpoint.<init>(JavaExceptionBreakpoint.java:186)
	at org.eclipse.jdt.debug.core.JDIDebugModel.createExceptionBreakpoint(JDIDebugModel.java:630)
	at org.eclipse.jdt.internal.debug.ui.JavaDebugOptionsManager$InitJob.run(JavaDebugOptionsManager.java:177)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```
I suggest you check eclipse-jst instead.

**Comment by merks** [comment]
FYI, I mentioned this stack trace on the EPP dev list from testing the JEE RC1 package:

https://www.eclipse.org/lists/epp-dev/msg06800.html

**Comment by olkornii** [comment]
> @olkornii can you add the [RC2a](https://download.eclipse.org/eclipse/downloads/drops4/S-4.29RC2a-202309031000/) p2 update site `https://download.eclipse.org/eclipse/updates/4.29-I-builds/I20230903-1000/` to your [available software sites](https://help.eclipse.org/latest/topic/org.eclipse.platform.doc.user/tasks/tasks-128.htm), check for updates and restart and see if you can still reproduce the problem?

I've tried next steps:
1. Download Eclipse IDE for Enterprise Java and Web Developers RC1
2. Window -> Preferences -> Available Software -> Remove all;
3. Open Error Log
4. install RedDeer with actual update site (ex. https://download.eclipse.org/reddeer/releases/4.7.0/) -> restart IDE
5. Create RD project: file -> new -> other -> RedDeer Test Plug-in -> some text to every field (ex. "myproj") -> Example test checkbox: CHECK -> Finish
**6. Delete project -> Your steps -> repeat step 5**
7. Right click on project in project explorer -> Run as RedDeer test -> see Error log

No changes, errors appears.

**Comment by olkornii** [comment]
> FYI, I mentioned this stack trace on the EPP dev list from testing the JEE RC1 package:
> 
> https://www.eclipse.org/lists/epp-dev/msg06800.html

@merks 
I'm not very familiar with this so I don't know what "epp-dev" is, but it seems to be the same problem I'm having. So as I understand this is a known issue and you already reported it, right?

**Comment by merks** [comment]
It's the mailing list for this project, which is the project that produces all the packages on the download page:

https://github.com/eclipse-packaging

I have tested and confirmed that the problem from your stack traces  is fixed in the RC2 package:

https://www.eclipse.org/lists/epp-dev/msg06814.html

If you update using these two repositories as available and enabled repositories in the update site preferences;

- https://download.eclipse.org/technology/epp/packages/2023-09/202309071200
- https://download.eclipse.org/releases/2023-09/202309131000

then you will be updating to the fixed version that will be released on Wednesday.

**Comment by olkornii** [comment]
> It's the mailing list for this project, which is the project that produces all the packages on the download page:
> 
> https://github.com/eclipse-packaging
> 
> I have tested and confirmed that the problem from your stack traces is fixed in the RC2 package:
> 
> https://www.eclipse.org/lists/epp-dev/msg06814.html
> 
> If you update using these two repositories as available and enabled repositories in the update site preferences;
> 
> * https://download.eclipse.org/technology/epp/packages/2023-09/202309071200
> * https://download.eclipse.org/releases/2023-09/202309131000
> 
> then you will be updating to the fixed version that will be released on Wednesday.

@merks 
I added next repos to Available Software Sites:
https://download.eclipse.org/technology/epp/packages/2023-09/202309071200
https://download.eclipse.org/releases/2023-09/202309131000

**Then: Help -> Check for Updates -> Restart -> recreate the project and run -> Errors still appear.**

I'll wait for RC2 release and try again on Wednesday, mb something is broken locally.

**Comment by olkornii** [comment]
@merks 
makes sense? I have no other ideas...

**Comment by merks** [comment]
This is the broken version 1.2.901.v202307260438:

https://download.eclipse.org/releases/2023-09/202309011000/buildInfo/archive/download.eclipse.org/releases/2023-09/202309011000/index/org.eclipse.jst.j2ee_1.2.901.v202307260438.html

and this is the newer fixed version 1.2.901.v202309012304:

https://download.eclipse.org/releases/2023-09/202309131000/buildInfo/archive/download.eclipse.org/releases/2023-09/202309131000/index/org.eclipse.jst.j2ee_1.2.901.v202309012304.html

So the help about info should show this if you have the latest installed/updated:

![image](https://github.com/eclipse-pde/eclipse.pde/assets/208716/099eccf6-f183-4d88-a98f-50e9219ea68a)

I don't know their feature structure well enough to suggest what you might try to install from https://download.eclipse.org/releases/2023-09/202309131000 which would turn it into an update request...

**Comment by olkornii** [comment]
@merks Build id is same as your, but org.eclipse.jst.j2ee is not same:
![Screenshot from 2023-09-04 09-25-53](https://github.com/eclipse-pde/eclipse.pde/assets/60704619/f47a6b10-1035-4756-9d75-6048c3ce4f0f)
![Screenshot from 2023-09-11 11-29-46](https://github.com/eclipse-pde/eclipse.pde/assets/60704619/6d3ac0d6-2936-49ea-911d-2264837bd81a)

**Comment by olkornii** [comment]
@merks I have some very old version, for some reason...

**Comment by merks** [comment]
Yes, that's the older broken version.  I'm not sure how to force the update easily, or maybe even at all.  Looking at the features such as org.eclipse.jst.web_core.feature.feature.group which one might try to use for an update, that has an older version 3.31.0.v202307061452 so just doing a check for updates will not do an update on that because there is no newer version of that feature itself, though there are updates to bundles that it requires.

FYI @nitind

What might work to force an update is to use Help -> Perform Setup Tasks...

**Comment by olkornii** [comment]
@merks
Works for me. Thanks a lot :) So RC2 should not have any errors as well. To be sure, I'll check it as well.

So to summarize:
1. add Available Software Sites:
https://download.eclipse.org/technology/epp/packages/2023-09/202309071200
https://download.eclipse.org/releases/2023-09/202309131000
2. Check for Updates
3. Perform Setup Tasks...
Done. 

During "Check for Updates" or "Perform Setup Tasks" I got another error, but I don't think it is important:
'''
eclipse.buildId=4.29.0.20230907-1200
java.version=17.0.8.1
java.vendor=Eclipse Adoptium
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_GB
Framework arguments:  -product org.eclipse.epp.package.jee.product
Command-line arguments:  -data file:/home/olkornii/eclipse-workspace-final_test_rd_fixes_jst/ -os linux -ws gtk -arch x86_64 -product org.eclipse.epp.package.jee.product

org.eclipse.equinox.p2.artifact.repository
Error
Mon Sep 11 12:19:49 CEST 2023
No repository found at file:/home/olkornii/.p2/pool.
'''

**Comment by merks** [comment]
I'm not sure exactly what causes that, but I see such logged exceptions when I generate Oomph's catalogs too.  In any case, it's indeed completely harmless noise (that I'll need to track down one day).

I'm glad you were able to update your installation and verify the fix!

**Comment by HannesWell** [comment]
@olkornii please don't hijack issues to discuss completly unrelated other problems.
Either do that at the issue tracker of the affected project or if you don't know the right specific place, ask at a common place like:
https://github.com/eclipse-platform/.github/issues

Thank you.
